version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "${REGISTRY}${CONTAINER_NAME}:${TAG}"
    container_name: ${CONTAINER_NAME}
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file:
      - .env.prod
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    restart: always
    command: ["sh", "/home/node/app/entrypoint.sh"]

  db:
    image: postgres:16
    container_name: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: Asia/Jakarta
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
