# Base Image
FROM node:20-alpine as base

# Install PostgreSQL client untuk pg_isready
RUN apk add --no-cache postgresql-client

# Set Workdir
WORKDIR /home/node/app

# Copy package.json dan package-lock.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy semua file ke dalam container
COPY . .

# Install Nodemon
RUN npm install -g nodemon

# Salin entrypoint script & beri izin eksekusi
COPY entrypoint.sh /home/node/app/entrypoint.sh

# Ubah ke root untuk memberikan izin eksekusi
USER root
RUN chmod +x /home/node/app/entrypoint.sh

# Kembalikan ke user node
USER node

# Gunakan entrypoint script
CMD ["sh", "/home/node/app/entrypoint.sh", "nodemon", "server.js"]

